/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pedidos: Pedido;
    produtos: Produto;
    categorias: Categoria;
    lojas: Loja;
    media: Media;
    users: User;
    clientes: Cliente;
    cupons: Cupon;
    carrinhos: Carrinho;
    entregadores: Entregadore;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pedidos: PedidosSelect<false> | PedidosSelect<true>;
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    lojas: LojasSelect<false> | LojasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    cupons: CuponsSelect<false> | CuponsSelect<true>;
    carrinhos: CarrinhosSelect<false> | CarrinhosSelect<true>;
    entregadores: EntregadoresSelect<false> | EntregadoresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username?: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos".
 */
export interface Pedido {
  id: number;
  loja?: (number | null) | Loja;
  numero: number;
  status: 'novo' | 'preparando' | 'pronto' | 'entregue' | 'cancelado';
  itens: {
    nome: string;
    opcoes?: string | null;
    produto?: number | null;
    escolhas?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    quantidade: number;
    precoUnitario: number;
    id?: string | null;
  }[];
  subtotal: number;
  taxa: number;
  promocao?: number | null;
  desconto?: number | null;
  cupom?: string | null;
  total: number;
  modo: 'entrega' | 'retirada';
  mesa?: string | null;
  garcom?: (number | null) | User;
  pediuConta?: boolean | null;
  contaFechada?: boolean | null;
  balcao?: boolean | null;
  nome: string;
  telefone?: string | null;
  codigoRetirada?: string | null;
  endereco?: string | null;
  entregador?: (number | null) | Entregadore;
  agendadoPara?: string | null;
  pagamento?: ('pix' | 'cartao' | 'dinheiro') | null;
  trocoPara?: number | null;
  cpf?: string | null;
  observacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas".
 */
export interface Loja {
  id: number;
  nome: string;
  /**
   * Só letras minúsculas, números e hífen. Ex.: cantina-dona-lurdes
   */
  slug: string;
  /**
   * Com DDD. Ex.: (31) 99999-0000
   */
  whatsapp: string;
  /**
   * Formato #rrggbb. Ex.: #9a3b1e
   */
  corPrincipal?: string | null;
  fonte?: ('classica' | 'moderna' | 'tradicional' | 'leve') | null;
  logo?: (number | null) | Media;
  /**
   * Opcional. Foto larga (deitada) que aparece no topo do cardápio.
   */
  capa?: (number | null) | Media;
  /**
   * Ex.: 11h às 15h
   */
  horario?: string | null;
  endereco?: string | null;
  fazEntrega?: boolean | null;
  /**
   * Vale quando não há bairros cadastrados abaixo.
   */
  taxaEntrega?: number | null;
  aceitaRetirada?: boolean | null;
  /**
   * O cliente pode escolher dia e hora (de 1 hora até 7 dias à frente).
   */
  aceitaAgendamento?: boolean | null;
  /**
   * Quantidade ("10" vira as mesas 1 a 10) ou nomes separados por vírgula. Cada mesa tem um QR Code no painel.
   */
  mesas?: string | null;
  atendimentoMesas?: ('ambos' | 'garcom' | 'cliente') | null;
  instrucoesMesa?: string | null;
  /**
   * Se tiver algum bairro aqui, a loja entrega só nestes, cada um com a sua taxa.
   */
  bairros?:
    | {
        nome: string;
        taxa: number;
        id?: string | null;
      }[]
    | null;
  /**
   * O cliente escolhe uma destas ao fazer o pedido.
   */
  formasPagamento: ('pix' | 'cartao' | 'dinheiro')[];
  /**
   * Aparece para o cliente copiar quando ele escolhe Pix.
   */
  chavePix?: string | null;
  /**
   * Só os números do ID do Pixel. Opcional.
   */
  pixelMeta?: string | null;
  /**
   * G-XXXXXXXXXX (Analytics) ou AW-XXXXXXXXXX (Ads). Opcional.
   */
  tagGoogle?: string | null;
  /**
   * Desmarque para pausar os pedidos (o cardápio continua visível).
   */
  aberta?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  loja?: (number | null) | Loja;
  /**
   * Opcional. Em branco, usamos o nome do arquivo.
   */
  alt?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'loja' | 'garcom')[];
  lojaDoGarcom?: (number | null) | Loja;
  nome?: string | null;
  ativo?: boolean | null;
  tenants?:
    | {
        tenant: number | Loja;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entregadores".
 */
export interface Entregadore {
  id: number;
  loja?: (number | null) | Loja;
  nome: string;
  whatsapp: string;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  loja?: (number | null) | Loja;
  nome: string;
  descricao?: string | null;
  preco: number;
  categoria: number | Categoria;
  foto?: (number | null) | Media;
  /**
   * Ex.: leve 3 e pague 2.
   */
  leve?: number | null;
  pague?: number | null;
  /**
   * Etiquetas que aparecem junto do nome no cardápio.
   */
  selos?: ('mais-pedido' | 'novo' | 'promocao' | 'vegano' | 'picante')[] | null;
  /**
   * Ex.: Tamanho (escolha 1), Borda, Extras (até 3). O painel da loja edita isto em texto.
   */
  opcoes?:
    | {
        nome: string;
        min?: number | null;
        max?: number | null;
        itens: {
          nome: string;
          preco?: number | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Continua no cardápio, mas não dá para pedir.
   */
  esgotado?: boolean | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  loja?: (number | null) | Loja;
  nome: string;
  /**
   * Menor aparece primeiro.
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  /**
   * Só DDD + número, sem 55. Ex.: 31999990000
   */
  telefone: string;
  nome: string;
  aceitouEm?: string | null;
  enderecos?:
    | {
        rua: string;
        complemento?: string | null;
        bairro: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupons".
 */
export interface Cupon {
  id: number;
  loja?: (number | null) | Loja;
  codigo: string;
  tipo: 'porcentagem' | 'valor';
  valor: number;
  minimo?: number | null;
  validoAte?: string | null;
  limiteUso?: number | null;
  usos?: number | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carrinhos".
 */
export interface Carrinho {
  id: number;
  loja?: (number | null) | Loja;
  telefone: string;
  nome: string;
  resumo: string;
  total: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pedidos';
        value: number | Pedido;
      } | null)
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'lojas';
        value: number | Loja;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'cupons';
        value: number | Cupon;
      } | null)
    | ({
        relationTo: 'carrinhos';
        value: number | Carrinho;
      } | null)
    | ({
        relationTo: 'entregadores';
        value: number | Entregadore;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos_select".
 */
export interface PedidosSelect<T extends boolean = true> {
  loja?: T;
  numero?: T;
  status?: T;
  itens?:
    | T
    | {
        nome?: T;
        opcoes?: T;
        produto?: T;
        escolhas?: T;
        quantidade?: T;
        precoUnitario?: T;
        id?: T;
      };
  subtotal?: T;
  taxa?: T;
  promocao?: T;
  desconto?: T;
  cupom?: T;
  total?: T;
  modo?: T;
  mesa?: T;
  garcom?: T;
  pediuConta?: T;
  contaFechada?: T;
  balcao?: T;
  nome?: T;
  telefone?: T;
  codigoRetirada?: T;
  endereco?: T;
  entregador?: T;
  agendadoPara?: T;
  pagamento?: T;
  trocoPara?: T;
  cpf?: T;
  observacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  loja?: T;
  nome?: T;
  descricao?: T;
  preco?: T;
  categoria?: T;
  foto?: T;
  leve?: T;
  pague?: T;
  selos?: T;
  opcoes?:
    | T
    | {
        nome?: T;
        min?: T;
        max?: T;
        itens?:
          | T
          | {
              nome?: T;
              preco?: T;
              id?: T;
            };
        id?: T;
      };
  esgotado?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  loja?: T;
  nome?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lojas_select".
 */
export interface LojasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  whatsapp?: T;
  corPrincipal?: T;
  fonte?: T;
  logo?: T;
  capa?: T;
  horario?: T;
  endereco?: T;
  fazEntrega?: T;
  taxaEntrega?: T;
  aceitaRetirada?: T;
  aceitaAgendamento?: T;
  mesas?: T;
  atendimentoMesas?: T;
  instrucoesMesa?: T;
  bairros?:
    | T
    | {
        nome?: T;
        taxa?: T;
        id?: T;
      };
  formasPagamento?: T;
  chavePix?: T;
  pixelMeta?: T;
  tagGoogle?: T;
  aberta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  loja?: T;
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  lojaDoGarcom?: T;
  nome?: T;
  ativo?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  telefone?: T;
  nome?: T;
  aceitouEm?: T;
  enderecos?:
    | T
    | {
        rua?: T;
        complemento?: T;
        bairro?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupons_select".
 */
export interface CuponsSelect<T extends boolean = true> {
  loja?: T;
  codigo?: T;
  tipo?: T;
  valor?: T;
  minimo?: T;
  validoAte?: T;
  limiteUso?: T;
  usos?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carrinhos_select".
 */
export interface CarrinhosSelect<T extends boolean = true> {
  loja?: T;
  telefone?: T;
  nome?: T;
  resumo?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entregadores_select".
 */
export interface EntregadoresSelect<T extends boolean = true> {
  loja?: T;
  nome?: T;
  whatsapp?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}